#!/bin/bash -ex

DOCKER_ARCH=${BUILD_ARCH:-arm32v7}
DOCKER_ORG=${DOCKER_ORG:-agners}
DOCKER_IMAGE=archlinuxarm-${DOCKER_ARCH}

TAG_DATE=$(date +'%Y%m%d')

docker build -t $DOCKER_ORG/$DOCKER_IMAGE \
	-t $DOCKER_ORG/$DOCKER_IMAGE:$TAG_DATE \
	-f Dockerfile.${DOCKER_ARCH} .

